# Generated by Django 2.1.7 on 2019-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='post',
            name='book_author',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
